// All countries
// length 252
export const categories = [
  { title: 'Afghanistan', code: 'AF' },
  { title: 'Aland Islands', code: 'AX' },
  { title: 'Albania', code: 'AL' },
  { title: 'Algeria', code: 'DZ' },
  { title: 'American Samoa', code: 'AS' },
  { title: 'Andorra', code: 'AD' },
  { title: 'Angola', code: 'AO' },
  { title: 'Anguilla', code: 'AI' },
  { title: 'Antarctica', code: 'AQ' },
  { title: 'Antigua and Barbuda', code: 'AG' },
  { title: 'Argentina', code: 'AR' },
  { title: 'Armenia', code: 'AM' },
  { title: 'Aruba', code: 'AW' },
  { title: 'Australia', code: 'AU' },
  { title: 'Austria', code: 'AT' },
  { title: 'Azerbaijan', code: 'AZ' },
  { title: 'Bahamas', code: 'BS' },
  { title: 'Bahrain', code: 'BH' },
  { title: 'Bangladesh', code: 'BD' },
  { title: 'Barbados', code: 'BB' },
  { title: 'Belarus', code: 'BY' },
  { title: 'Belgium', code: 'BE' },
  { title: 'Belize', code: 'BZ' },
  { title: 'Benin', code: 'BJ' },
  { title: 'Bermuda', code: 'BM' },
  { title: 'Bhutan', code: 'BT' },
  { title: 'Bolivia', code: 'BO' },
  { title: 'Bonaire, Sint Eustatius and Saba', code: 'BQ' },
  { title: 'Bosnia and Herzegovina', code: 'BA' },
  { title: 'Botswana', code: 'BW' },
  { title: 'Bouvet Island', code: 'BV' },
  { title: 'Brazil', code: 'BR' },
  { title: 'British Indian Ocean Territory', code: 'IO' },
  { title: 'Brunei Darussalam', code: 'BN' },
];
