// All countries
// length 252
export const countries = [
  { nameEn: 'Afghanistan', nameAr: 'أفغانستان', code: 'AF' },
  { nameEn: 'Aland Islands', nameAr: 'جزر آلاند', code: 'AX' },
  { nameEn: 'Albania', nameAr: 'ألبانيا', code: 'AL' },
  { nameEn: 'Algeria', nameAr: 'الجزائر', code: 'DZ' },
  { nameEn: 'American Samoa', nameAr: 'ساموا الأمريكية', code: 'AS' },
  { nameEn: 'Andorra', nameAr: 'أندورا', code: 'AD' },
  { nameEn: 'Angola', nameAr: 'أنغولا', code: 'AO' },
  { nameEn: 'Anguilla', nameAr: 'أنغيلا', code: 'AI' },
  { nameEn: 'Antarctica', nameAr: 'أنتاركتيكا', code: 'AQ' },
  { nameEn: 'Antigua and Barbuda', nameAr: 'أنتيغوا وبربودا', code: 'AG' },
  { nameEn: 'Argentina', nameAr: 'الأرجنتين', code: 'AR' },
  { nameEn: 'Armenia', nameAr: 'أرمينيا', code: 'AM' },
  { nameEn: 'Aruba', nameAr: 'أروبا', code: 'AW' },
  { nameEn: 'Australia', nameAr: 'أستراليا', code: 'AU' },
  { nameEn: 'Austria', nameAr: 'النمسا', code: 'AT' },
  { nameEn: 'Azerbaijan', nameAr: 'أذربيجان', code: 'AZ' },
  { nameEn: 'Bahamas', nameAr: 'جزر البهاما', code: 'BS' },
  { nameEn: 'Bahrain', nameAr: 'البحرين', code: 'BH' },
  { nameEn: 'Bangladesh', nameAr: 'بنغلاديش', code: 'BD' },
  { nameEn: 'Barbados', nameAr: 'بربادوس', code: 'BB' },
  { nameEn: 'Belarus', nameAr: 'بيلاروسيا', code: 'BY' },
  { nameEn: 'Belgium', nameAr: 'بلجيكا', code: 'BE' },
  { nameEn: 'Belize', nameAr: 'بليز', code: 'BZ' },
  { nameEn: 'Benin', nameAr: 'بنين', code: 'BJ' },
  { nameEn: 'Bermuda', nameAr: 'برمودا', code: 'BM' },
  { nameEn: 'Bhutan', nameAr: 'بوتان', code: 'BT' },
  { nameEn: 'Bolivia', nameAr: 'بوليفيا', code: 'BO' },
  { nameEn: 'Bonaire, Sint Eustatius and Saba', nameAr: 'بونير وسانت يوستاتيوس وسابا', code: 'BQ' },
  { nameEn: 'Bosnia and Herzegovina', nameAr: 'البوسنة والهرسك', code: 'BA' },
  { nameEn: 'Botswana', nameAr: 'بوتسوانا', code: 'BW' },
  { nameEn: 'Bouvet Island', nameAr: 'جزيرة بوفيت', code: 'BV' },
  { nameEn: 'Brazil', nameAr: 'البرازيل', code: 'BR' },
  { nameEn: 'British Indian Ocean Territory', nameAr: 'إقليم المحيط البريطاني الهندي', code: 'IO' },
  { nameEn: 'Brunei Darussalam', nameAr: 'بروناي دار السلام', code: 'BN' },
  { nameEn: 'Bulgaria', nameAr: 'بلغاريا', code: 'BG' },
  { nameEn: 'Burkina Faso', nameAr: 'بوركينا فاسو', code: 'BF' },
  { nameEn: 'Burundi', nameAr: 'بوروندي', code: 'BI' },
  { nameEn: 'Cambodia', nameAr: 'كمبوديا', code: 'KH' },
  { nameEn: 'Cameroon', nameAr: 'الكاميرون', code: 'CM' },
  { nameEn: 'Canada', nameAr: 'كندا', code: 'CA' },
  { nameEn: 'Cape Verde', nameAr: 'الرأس الأخضر', code: 'CV' },
  { nameEn: 'Cayman Islands', nameAr: 'جزر كايمان', code: 'KY' },
  { nameEn: 'Central African Republic', nameAr: 'جمهورية افريقيا الوسطى', code: 'CF' },
  { nameEn: 'Chad', nameAr: 'تشاد', code: 'TD' },
  { nameEn: 'Chile', nameAr: 'تشيلي', code: 'CL' },
  { nameEn: 'China', nameAr: 'الصين', code: 'CN' },
  { nameEn: 'Christmas Island', nameAr: 'جزيرة الكريسماس', code: 'CX' },
  { nameEn: 'Cocos (Keeling) Islands', nameAr: 'جزر كوكوس (كيلينغ)', code: 'CC' },
  { nameEn: 'Colombia', nameAr: 'كولومبيا', code: 'CO' },
  { nameEn: 'Comoros', nameAr: 'جزر القمر', code: 'KM' },
  { nameEn: 'Congo', nameAr: 'الكونغو', code: 'CG' },
  { nameEn: 'Congo, Democratic Republic of the Congo', nameAr: 'الكونغو ، جمهورية الكونغو الديمقراطية', code: 'CD' },
  { nameEn: 'Cook Islands', nameAr: 'جزر كوك', code: 'CK' },
  { nameEn: 'Costa Rica', nameAr: 'كوستا ريكا', code: 'CR' },
  { nameEn: "Cote D'Ivoire", code: 'CI' },
  { nameEn: 'Croatia', nameAr: 'كرواتيا', code: 'HR' },
  { nameEn: 'Cuba', nameAr: 'كوبا', code: 'CU' },
  { nameEn: 'Curacao', nameAr: 'كوراكاو', code: 'CW' },
  { nameEn: 'Cyprus', nameAr: 'قبرص', code: 'CY' },
  { nameEn: 'Czech Republic', nameAr: 'الجمهورية التشيكية', code: 'CZ' },
  { nameEn: 'Denmark', nameAr: 'الدنمارك', code: 'DK' },
  { nameEn: 'Djibouti', nameAr: 'جيبوتي', code: 'DJ' },
  { nameEn: 'Dominica', nameAr: 'دومينيكا', code: 'DM' },
  { nameEn: 'Dominican Republic', nameAr: 'جمهورية الدومينيكان', code: 'DO' },
  { nameEn: 'Ecuador', nameAr: 'الاكوادور', code: 'EC' },
  { nameEn: 'Egypt', nameAr: 'مصر', code: 'EG' },
  { nameEn: 'El Salvador', nameAr: 'السلفادور', code: 'SV' },
  { nameEn: 'Equatorial Guinea', nameAr: 'غينيا الإستوائية', code: 'GQ' },
  { nameEn: 'Eritrea', nameAr: 'إريتريا', code: 'ER' },
  { nameEn: 'Estonia', nameAr: 'إستونيا', code: 'EE' },
  { nameEn: 'Ethiopia', nameAr: 'أثيوبيا', code: 'ET' },
  { nameEn: 'Falkland Islands (Malvinas)', nameAr: 'جزر فوكلاند (مالفيناس)', code: 'FK' },
  { nameEn: 'Faroe Islands', nameAr: 'جزر فاروس', code: 'FO' },
  { nameEn: 'Fiji', nameAr: 'فيجي', code: 'FJ' },
  { nameEn: 'Finland', nameAr: 'فنلندا', code: 'FI' },
  { nameEn: 'France', nameAr: 'فرنسا', code: 'FR' },
  { nameEn: 'French Guiana', nameAr: 'غيانا الفرنسية', code: 'GF' },
  { nameEn: 'French Polynesia', nameAr: 'بولينيزيا الفرنسية', code: 'PF' },
  { nameEn: 'French Southern Territories', nameAr: 'المناطق الجنوبية لفرنسا', code: 'TF' },
  { nameEn: 'Gabon', nameAr: 'الجابون', code: 'GA' },
  { nameEn: 'Gambia', nameAr: 'غامبيا', code: 'GM' },
  { nameEn: 'Georgia', nameAr: 'جورجيا', code: 'GE' },
  { nameEn: 'Germany', nameAr: 'ألمانيا', code: 'DE' },
  { nameEn: 'Ghana', nameAr: 'غانا', code: 'GH' },
  { nameEn: 'Gibraltar', nameAr: 'جبل طارق', code: 'GI' },
  { nameEn: 'Greece', nameAr: 'اليونان', code: 'GR' },
  { nameEn: 'Greenland', nameAr: 'الأرض الخضراء', code: 'GL' },
  { nameEn: 'Grenada', nameAr: 'غرينادا', code: 'GD' },
  { nameEn: 'Guadeloupe', nameAr: 'جوادلوب', code: 'GP' },
  { nameEn: 'Guam', nameAr: 'غوام', code: 'GU' },
  { nameEn: 'Guatemala', nameAr: 'غواتيمالا', code: 'GT' },
  { nameEn: 'Guernsey', nameAr: 'غيرنسي', code: 'GG' },
  { nameEn: 'Guinea', nameAr: 'غينيا', code: 'GN' },
  { nameEn: 'Guinea-Bissau', nameAr: 'غينيا بيساو', code: 'GW' },
  { nameEn: 'Guyana', nameAr: 'غيانا', code: 'GY' },
  { nameEn: 'Haiti', nameAr: 'هايتي', code: 'HT' },
  { nameEn: 'Heard Island and Mcdonald Islands', nameAr: 'قلب الجزيرة وجزر ماكدونالز', code: 'HM' },
  { nameEn: 'Holy See (Vatican City State)', nameAr: 'الكرسي الرسولي (دولة الفاتيكان)', code: 'VA' },
  { nameEn: 'Honduras', nameAr: 'هندوراس', code: 'HN' },
  { nameEn: 'Hong Kong', nameAr: 'هونج كونج', code: 'HK' },
  { nameEn: 'Hungary', nameAr: 'هنغاريا', code: 'HU' },
  { nameEn: 'Iceland', nameAr: 'أيسلندا', code: 'IS' },
  { nameEn: 'India', nameAr: 'الهند', code: 'IN' },
  { nameEn: 'Indonesia', nameAr: 'إندونيسيا', code: 'ID' },
  { nameEn: 'Iran, Islamic Republic of', nameAr: 'جمهورية إيران الإسلامية', code: 'IR' },
  { nameEn: 'Iraq', nameAr: 'العراق', code: 'IQ' },
  { nameEn: 'Ireland', nameAr: 'أيرلندا', code: 'IE' },
  { nameEn: 'Isle of Man', nameAr: 'جزيرة آيل أوف مان', code: 'IM' },
  { nameEn: 'Israel', nameAr: 'إسرائيل', code: 'IL' },
  { nameEn: 'Italy', nameAr: 'إيطاليا', code: 'IT' },
  { nameEn: 'Jamaica', nameAr: 'جامايكا', code: 'JM' },
  { nameEn: 'Japan', nameAr: 'اليابان', code: 'JP' },
  { nameEn: 'Jersey', nameAr: 'جيرسي', code: 'JE' },
  { nameEn: 'Jordan', nameAr: 'الأردن', code: 'JO' },
  { nameEn: 'Kazakhstan', nameAr: 'كازاخستان', code: 'KZ' },
  { nameEn: 'Kenya', nameAr: 'كينيا', code: 'KE' },
  { nameEn: 'Kiribati', nameAr: 'كيريباتي', code: 'KI' },
  { nameEn: "Korea, Democratic People's Republic of", code: 'KP' },
  { nameEn: 'Korea, Republic of', nameAr: 'جمهورية كوريا', code: 'KR' },
  { nameEn: 'Kosovo', nameAr: 'كوسوفو', code: 'XK' },
  { nameEn: 'Kuwait', nameAr: 'الكويت', code: 'KW' },
  { nameEn: 'Kyrgyzstan', nameAr: 'قيرغيزستان', code: 'KG' },
  { nameEn: "Lao People's Democratic Republic", code: 'LA' },
  { nameEn: 'Latvia', nameAr: 'لاتفيا', code: 'LV' },
  { nameEn: 'Lebanon', nameAr: 'لبنان', code: 'LB' },
  { nameEn: 'Lesotho', nameAr: 'ليسوتو', code: 'LS' },
  { nameEn: 'Liberia', nameAr: 'ليبيريا', code: 'LR' },
  { nameEn: 'Libyan Arab Jamahiriya', nameAr: 'الجماهيرية العربية الليبية', code: 'LY' },
  { nameEn: 'Liechtenstein', nameAr: 'ليختنشتاين', code: 'LI' },
  { nameEn: 'Lithuania', nameAr: 'ليتوانيا', code: 'LT' },
  { nameEn: 'Luxembourg', nameAr: 'لوكسمبورغ', code: 'LU' },
  { nameEn: 'Macao', nameAr: 'ماكاو', code: 'MO' },
  { nameEn: 'Macedonia, the Former Yugoslav Republic of', nameAr: 'مقدونيا ، جمهورية يوغوسلافيا السابقة', code: 'MK' },
  { nameEn: 'Madagascar', nameAr: 'مدغشقر', code: 'MG' },
  { nameEn: 'Malawi', nameAr: 'ملاوي', code: 'MW' },
  { nameEn: 'Malaysia', nameAr: 'ماليزيا', code: 'MY' },
  { nameEn: 'Maldives', nameAr: 'جزر المالديف', code: 'MV' },
  { nameEn: 'Mali', nameAr: 'مالي', code: 'ML' },
  { nameEn: 'Malta', nameAr: 'مالطا', code: 'MT' },
  { nameEn: 'Marshall Islands', nameAr: 'جزر مارشال', code: 'MH' },
  { nameEn: 'Martinique', nameAr: 'مارتينيك', code: 'MQ' },
  { nameEn: 'Mauritania', nameAr: 'موريتانيا', code: 'MR' },
  { nameEn: 'Mauritius', nameAr: 'موريشيوس', code: 'MU' },
  { nameEn: 'Mayotte', nameAr: 'مايوت', code: 'YT' },
  { nameEn: 'Mexico', nameAr: 'المكسيك', code: 'MX' },
  { nameEn: 'Micronesia, Federated States of', nameAr: 'ولايات ميكرونيزيا الموحدة', code: 'FM' },
  { nameEn: 'Moldova, Republic of', nameAr: 'جمهورية مولدوفا', code: 'MD' },
  { nameEn: 'Monaco', nameAr: 'موناكو', code: 'MC' },
  { nameEn: 'Mongolia', nameAr: 'منغوليا', code: 'MN' },
  { nameEn: 'Montenegro', nameAr: 'الجبل الأسود', code: 'ME' },
  { nameEn: 'Montserrat', nameAr: 'مونتسيرات', code: 'MS' },
  { nameEn: 'Morocco', nameAr: 'المغرب', code: 'MA' },
  { nameEn: 'Mozambique', nameAr: 'موزمبيق', code: 'MZ' },
  { nameEn: 'Myanmar', nameAr: 'ميانمار', code: 'MM' },
  { nameEn: 'Namibia', nameAr: 'ناميبيا', code: 'NA' },
  { nameEn: 'Nauru', nameAr: 'ناورو', code: 'NR' },
  { nameEn: 'Nepal', nameAr: 'نيبال', code: 'NP' },
  { nameEn: 'Netherlands', nameAr: 'هولندا', code: 'NL' },
  { nameEn: 'Netherlands Antilles', nameAr: 'جزر الأنتيل الهولندية', code: 'AN' },
  { nameEn: 'New Caledonia', nameAr: 'كاليدونيا الجديدة', code: 'NC' },
  { nameEn: 'New Zealand', nameAr: 'نيوزيلاندا', code: 'NZ' },
  { nameEn: 'Nicaragua', nameAr: 'نيكاراغوا', code: 'NI' },
  { nameEn: 'Niger', nameAr: 'النيجر', code: 'NE' },
  { nameEn: 'Nigeria', nameAr: 'نيجيريا', code: 'NG' },
  { nameEn: 'Niue', nameAr: 'نيوي', code: 'NU' },
  { nameEn: 'Norfolk Island', nameAr: 'جزيرة نورفولك', code: 'NF' },
  { nameEn: 'Northern Mariana Islands', nameAr: 'جزر مريانا الشمالية', code: 'MP' },
  { nameEn: 'Norway', nameAr: 'النرويج', code: 'NO' },
  { nameEn: 'Oman', nameAr: 'سلطنة عمان', code: 'OM' },
  { nameEn: 'Pakistan', nameAr: 'باكستان', code: 'PK' },
  { nameEn: 'Palau', nameAr: 'بالاو', code: 'PW' },
  { nameEn: 'Palestinian Territory, Occupied', nameAr: 'الأراضي الفلسطينية المحتلة', code: 'PS' },
  { nameEn: 'Panama', nameAr: 'بنما', code: 'PA' },
  { nameEn: 'Papua New Guinea', nameAr: 'بابوا غينيا الجديدة', code: 'PG' },
  { nameEn: 'Paraguay', nameAr: 'باراغواي', code: 'PY' },
  { nameEn: 'Peru', nameAr: 'بيرو', code: 'PE' },
  { nameEn: 'Philippines', nameAr: 'فيلبيني', code: 'PH' },
  { nameEn: 'Pitcairn', nameAr: 'بيتكيرن', code: 'PN' },
  { nameEn: 'Poland', nameAr: 'بولندا', code: 'PL' },
  { nameEn: 'Portugal', nameAr: 'البرتغال', code: 'PT' },
  { nameEn: 'Puerto Rico', nameAr: 'بورتوريكو', code: 'PR' },
  { nameEn: 'Qatar', nameAr: 'دولة قطر', code: 'QA' },
  { nameEn: 'Reunion', nameAr: 'جمع شمل', code: 'RE' },
  { nameEn: 'Romania', nameAr: 'رومانيا', code: 'RO' },
  { nameEn: 'Russian Federation', nameAr: 'الاتحاد الروسي', code: 'RU' },
  { nameEn: 'Rwanda', nameAr: 'رواندا', code: 'RW' },
  { nameEn: 'Saint Barthelemy', nameAr: 'سانت بارتيليمي', code: 'BL' },
  { nameEn: 'Saint Helena', nameAr: 'سانت هيلانة', code: 'SH' },
  { nameEn: 'Saint Kitts and Nevis', nameAr: 'سانت كيتس ونيفيس', code: 'KN' },
  { nameEn: 'Saint Lucia', nameAr: 'القديسة لوسيا', code: 'LC' },
  { nameEn: 'Saint Martin', nameAr: 'القديس مارتن', code: 'MF' },
  { nameEn: 'Saint Pierre and Miquelon', nameAr: 'سانت بيير وميكلون', code: 'PM' },
  { nameEn: 'Saint Vincent and the Grenadines', nameAr: 'سانت فنسنت وجزر غرينادين', code: 'VC' },
  { nameEn: 'Samoa', nameAr: 'ساموا', code: 'WS' },
  { nameEn: 'San Marino', nameAr: 'سان مارينو', code: 'SM' },
  { nameEn: 'Sao Tome and Principe', nameAr: 'ساو تومي وبرينسيبي', code: 'ST' },
  { nameEn: 'Saudi Arabia', nameAr: 'المملكة العربية السعودية', code: 'SA' },
  { nameEn: 'Senegal', nameAr: 'السنغال', code: 'SN' },
  { nameEn: 'Serbia', nameAr: 'صربيا', code: 'RS' },
  { nameEn: 'Serbia and Montenegro', nameAr: 'صربيا والجبل الأسود', code: 'CS' },
  { nameEn: 'Seychelles', nameAr: 'سيشيل', code: 'SC' },
  { nameEn: 'Sierra Leone', nameAr: 'سيرا ليون', code: 'SL' },
  { nameEn: 'Singapore', nameAr: 'سنغافورة', code: 'SG' },
  { nameEn: 'Sint Maarten', nameAr: 'سينت مارتن', code: 'SX' },
  { nameEn: 'Slovakia', nameAr: 'سلوفاكيا', code: 'SK' },
  { nameEn: 'Slovenia', nameAr: 'سلوفينيا', code: 'SI' },
  { nameEn: 'Solomon Islands', nameAr: 'جزر سليمان', code: 'SB' },
  { nameEn: 'Somalia', nameAr: 'الصومال', code: 'SO' },
  { nameEn: 'South Africa', nameAr: 'جنوب أفريقيا', code: 'ZA' },
  { nameEn: 'South Georgia and the South Sandwich Islands', nameAr: 'جورجيا الجنوبية وجزر ساندويتش الجنوبية', code: 'GS' },
  { nameEn: 'South Sudan', nameAr: 'جنوب السودان', code: 'SS' },
  { nameEn: 'Spain', nameAr: 'إسبانيا', code: 'ES' },
  { nameEn: 'Sri Lanka', nameAr: 'سيريلانكا', code: 'LK' },
  { nameEn: 'Sudan', nameAr: 'السودان', code: 'SD' },
  { nameEn: 'Suriname', nameAr: 'سورينام', code: 'SR' },
  { nameEn: 'Svalbard and Jan Mayen', nameAr: 'سفالبارد وجان ماين', code: 'SJ' },
  { nameEn: 'Swaziland', nameAr: 'سوازيلاند', code: 'SZ' },
  { nameEn: 'Sweden', nameAr: 'السويد', code: 'SE' },
  { nameEn: 'Switzerland', nameAr: 'سويسرا', code: 'CH' },
  { nameEn: 'Syrian Arab Republic', nameAr: 'الجمهورية العربية السورية', code: 'SY' },
  { nameEn: 'Taiwan, Province of China', nameAr: 'مقاطعة تايوان الصينية', code: 'TW' },
  { nameEn: 'Tajikistan', nameAr: 'طاجيكستان', code: 'TJ' },
  { nameEn: 'Tanzania, United Republic of', nameAr: 'جمهورية تنزانيا المتحدة', code: 'TZ' },
  { nameEn: 'Thailand', nameAr: 'تايلاند', code: 'TH' },
  { nameEn: 'Timor-Leste', nameAr: 'تيمور ليشتي', code: 'TL' },
  { nameEn: 'Togo', nameAr: 'توجو', code: 'TG' },
  { nameEn: 'Tokelau', nameAr: 'توكيلاو', code: 'TK' },
  { nameEn: 'Tonga', nameAr: 'تونغا', code: 'TO' },
  { nameEn: 'Trinidad and Tobago', nameAr: 'ترينداد وتوباغو', code: 'TT' },
  { nameEn: 'Tunisia', nameAr: 'تونس', code: 'TN' },
  { nameEn: 'Turkey', nameAr: 'ديك رومى', code: 'TR' },
  { nameEn: 'Turkmenistan', nameAr: 'تركمانستان', code: 'TM' },
  { nameEn: 'Turks and Caicos Islands', nameAr: 'جزر تركس وكايكوس', code: 'TC' },
  { nameEn: 'Tuvalu', nameAr: 'توفالو', code: 'TV' },
  { nameEn: 'Uganda', nameAr: 'أوغندا', code: 'UG' },
  { nameEn: 'Ukraine', nameAr: 'أوكرانيا', code: 'UA' },
  { nameEn: 'United Arab Emirates', nameAr: 'الإمارات العربية المتحدة', code: 'AE' },
  { nameEn: 'United Kingdom', nameAr: 'المملكة المتحدة', code: 'GB' },
  { nameEn: 'United States', nameAr: 'الولايات المتحدة', code: 'US' },
  { nameEn: 'United States Minor Outlying Islands', nameAr: 'جزر الولايات المتحدة البعيدة الصغرى', code: 'UM' },
  { nameEn: 'Uruguay', nameAr: 'أوروغواي', code: 'UY' },
  { nameEn: 'Uzbekistan', nameAr: 'أوزبكستان', code: 'UZ' },
  { nameEn: 'Vanuatu', nameAr: 'فانواتو', code: 'VU' },
  { nameEn: 'Venezuela', nameAr: 'فنزويلا', code: 'VE' },
  { nameEn: 'Viet Nam', nameAr: 'فييت نام', code: 'VN' },
  { nameEn: 'Virgin Islands, British', nameAr: 'جزر العذراء البريطانية', code: 'VG' },
  { nameEn: 'Virgin Islands, U.s.', nameAr: 'جزر فيرجن ، الولايات المتحدة', code: 'VI' },
  { nameEn: 'Wallis and Futuna', nameAr: 'واليس وفوتونا', code: 'WF' },
  { nameEn: 'Western Sahara', nameAr: 'الصحراء الغربية', code: 'EH' },
  { nameEn: 'Yemen', nameAr: 'اليمن', code: 'YE' },
  { nameEn: 'Zambia', nameAr: 'زامبيا', code: 'ZM' },
  { nameEn: 'Zimbabwe', nameAr: 'زيمبابوي', code: 'ZW' },
];
