export const professions = [
  { name: 'Academic librarian', code: 12 },
  { name: 'Accountant', code: 12 },
  { name: 'Accounting technician', code: 12 },
  { name: 'Actuary', code: 12 },
  { name: 'Adult nurse', code: 12 },
  { name: 'Advertising account executive', code: 12 },
  { name: 'Advertising account planner', code: 12 },
  { name: 'Advertising copywriter', code: 12 },
  { name: 'Advice worker', code: 12 },
  { name: 'Advocate (Scotland)', code: 12 },
  { name: 'Aeronautical engineer', code: 12 },
  { name: 'Agricultural consultant', code: 12 },
  { name: 'Agricultural manager', code: 12 },
  { name: 'Aid worker/humanitarian worker', code: 12 },
  { name: 'Air traffic controller', code: 12 },
  { name: 'Airline cabin crew', code: 12 },
  { name: 'Amenity horticulturist', code: 12 },
  { name: 'Analytical chemist', code: 12 },
  { name: 'Animal nutritionist', code: 12 },
  { name: 'Animator', code: 12 },
  { name: 'Archaeologist', code: 12 },
  { name: 'Architect', code: 12 },
  { name: 'Architectural technologist', code: 12 },
  { name: 'Archivist', code: 12 },
  { name: 'Armed forces officer', code: 12 },
  { name: 'Aromatherapist', code: 12 },
  { name: 'Art therapist', code: 12 },
  { name: 'Arts administrator', code: 12 },
  { name: 'Auditor', code: 12 },
  { name: 'Automotive engineer', code: 12 },
  { name: 'Barrister', code: 12 },
  { name: 'Barrister’s clerk', code: 12 },
  { name: 'Bilingual secretary', code: 12 },
  { name: 'Biomedical engineer', code: 12 },
  { name: 'Biomedical scientist', code: 12 },
  { name: 'Biotechnologist', code: 12 },
  { name: 'Brand manager', code: 12 },
  { name: 'Broadcasting presenter', code: 12 },
  { name: 'Building control officer/surveyor', code: 12 },
  { name: 'Building services engineer', code: 12 },
  { name: 'Building surveyor', code: 12 },
  { name: 'Camera operator', code: 12 },
  { name: 'Careers adviser (higher education)', code: 12 },
  { name: 'Careers adviser', code: 12 },
  { name: 'Careers consultant', code: 12 },
  { name: 'Cartographer', code: 12 },
  { name: 'Catering manager', code: 12 },
  { name: 'Charities administrator', code: 12 },
  { name: 'Charities fundraiser', code: 12 },
  { name: 'Chemical (process) engineer', code: 12 },
  { name: 'Child psychotherapist', code: 12 },
  { name: "Children's nurse", code: 12 },
  { name: 'Chiropractor', code: 12 },
  { name: 'Civil engineer', code: 12 },
  { name: 'Civil Service administrator', code: 12 },
  { name: 'Clinical biochemist', code: 12 },
  { name: 'Clinical cytogeneticist', code: 12 },
  { name: 'Clinical microbiologist', code: 12 },
  { name: 'Clinical molecular geneticist', code: 12 },
  { name: 'Clinical research associate', code: 12 },
  { name: 'Clinical scientist - tissue typing', code: 12 },
  { name: 'Clothing and textile technologist', code: 12 },
  { name: 'Colour technologist', code: 12 },
  { name: 'Commercial horticulturist', code: 12 },
  { name: 'Commercial/residential/rural surveyor', code: 12 },
  { name: 'Commissioning editor', code: 12 },
  { name: 'Commissioning engineer', code: 12 },
  { name: 'Commodity broker', code: 12 },
  { name: 'Communications engineer', code: 12 },
  { name: 'Community arts worker', code: 12 },
  { name: 'Community education officer', code: 12 },
  { name: 'Community worker', code: 12 },
  { name: 'Company secretary', code: 12 },
  { name: 'Computer sales support', code: 12 },
  { name: 'Computer scientist', code: 12 },
  { name: 'Conference organiser', code: 12 },
  { name: 'Consultant', code: 12 },
  { name: 'Consumer rights adviser', code: 12 },
  { name: 'Control and instrumentation engineer', code: 12 },
  { name: 'Corporate banker', code: 12 },
  { name: 'Corporate treasurer', code: 12 },
  { name: 'Counsellor', code: 12 },
  { name: 'Courier/tour guide', code: 12 },
  { name: 'Court reporter/verbatim reporter', code: 12 },
  { name: 'Credit analyst', code: 12 },
  { name: 'Crown Prosecution Service lawyer', code: 12 },
  { name: 'Crystallographer', code: 12 },
  { name: 'Curator', code: 12 },
  { name: 'Customs officer', code: 12 },
  { name: 'Cyber security specialist', code: 12 },
  { name: 'Dance movement therapist', code: 12 },
  { name: 'Data analyst', code: 12 },
  { name: 'Data scientist', code: 12 },
  { name: 'Data visualisation analyst', code: 12 },
  { name: 'Database administrator', code: 12 },
  { name: 'Debt/finance adviser', code: 12 },
  { name: 'Dental hygienist', code: 12 },
  { name: 'Dentist', code: 12 },
  { name: 'Design engineer', code: 12 },
  { name: 'Dietitian', code: 12 },
  { name: 'Diplomatic service', code: 12 },
  { name: 'Doctor (general practitioner, GP)', code: 12 },
  { name: 'Doctor (hospital)', code: 12 },
  { name: 'Dramatherapist', code: 12 },
  { name: 'Economist', code: 12 },
  { name: 'Editorial assistant', code: 12 },
  { name: 'Education administrator', code: 12 },
  { name: 'Electrical engineer', code: 12 },
  { name: 'Electronics engineer', code: 12 },
  { name: 'Employment advice worker', code: 12 },
  { name: 'Energy conservation officer', code: 12 },
  { name: 'Engineering geologist', code: 12 },
  { name: 'Environmental education officer', code: 12 },
  { name: 'Environmental health officer', code: 12 },
  { name: 'Environmental manager', code: 12 },
  { name: 'Environmental scientist', code: 12 },
  { name: 'Equal opportunities officer', code: 12 },
  { name: 'Equality and diversity officer', code: 12 },
  { name: 'Ergonomist', code: 12 },
  { name: 'Estate agent', code: 12 },
  { name: 'European Commission administrators', code: 12 },
  { name: 'Exhibition display designer', code: 12 },
  { name: 'Exhibition organiser', code: 12 },
  { name: 'Exploration geologist', code: 12 },
  { name: 'Facilities manager', code: 12 },
  { name: 'Field trials officer', code: 12 },
  { name: 'Financial manager', code: 12 },
  { name: 'Firefighter', code: 12 },
  { name: 'Fisheries officer', code: 12 },
  { name: 'Fitness centre manager', code: 12 },
  { name: 'Food scientist', code: 12 },
  { name: 'Food technologist', code: 12 },
  { name: 'Forensic scientist', code: 12 },
  { name: 'Geneticist', code: 12 },
  { name: 'Geographical information systems manager', code: 12 },
  { name: 'Geomatics/land surveyor', code: 12 },
  { name: 'Government lawyer', code: 12 },
  { name: 'Government research officer', code: 12 },
  { name: 'Graphic designer', code: 12 },
  { name: 'Health and safety adviser', code: 12 },
  { name: 'Health and safety inspector', code: 12 },
  { name: 'Health promotion specialist', code: 12 },
  { name: 'Health service manager', code: 12 },
  { name: 'Health visitor', code: 12 },
  { name: 'Herbalist', code: 12 },
  { name: 'Heritage manager', code: 12 },
  { name: 'Higher education administrator', code: 12 },
  { name: 'Higher education advice worker', code: 12 },
  { name: 'Homeless worker', code: 12 },
  { name: 'Horticultural consultant', code: 12 },
  { name: 'Hotel manager', code: 12 },
  { name: 'Housing adviser', code: 12 },
  { name: 'Human resources officer', code: 12 },
  { name: 'Hydrologist', code: 12 },
  { name: 'Illustrator', code: 12 },
  { name: 'Immigration officer', code: 12 },
  { name: 'Immunologist', code: 12 },
  { name: 'Industrial/product designer', code: 12 },
  { name: 'Information scientist', code: 12 },
  { name: 'Information systems manager', code: 12 },
  { name: 'Information technology/software trainers', code: 12 },
  { name: 'Insurance broker', code: 12 },
  { name: 'Insurance claims inspector', code: 12 },
  { name: 'Insurance risk surveyor', code: 12 },
  { name: 'Insurance underwriter', code: 12 },
  { name: 'Interpreter', code: 12 },
  { name: 'Investment analyst', code: 12 },
  { name: 'Investment banker - corporate finance', code: 12 },
  { name: 'Investment banker – operations', code: 12 },
  { name: 'Investment fund manager', code: 12 },
  { name: 'IT consultant', code: 12 },
  { name: 'IT support analyst', code: 12 },
  { name: 'Journalist', code: 12 },
  { name: 'Laboratory technician', code: 12 },
  { name: 'Land-based engineer', code: 12 },
  { name: 'Landscape architect', code: 12 },
  { name: 'Learning disability nurse', code: 12 },
  { name: 'Learning mentor', code: 12 },
  { name: 'Lecturer (adult education)', code: 12 },
  { name: 'Lecturer (further education)', code: 12 },
  { name: 'Lecturer (higher education)', code: 12 },
  { name: 'Legal executive', code: 12 },
  { name: 'Leisure centre manager', code: 12 },
  { name: 'Licensed conveyancer', code: 12 },
  { name: 'Local government administrator', code: 12 },
  { name: 'Local government lawyer', code: 12 },
  { name: 'Logistics/distribution manager', code: 12 },
  { name: 'Magazine features editor', code: 12 },
  { name: 'Magazine journalist', code: 12 },
  { name: 'Maintenance engineer', code: 12 },
  { name: 'Management accountant', code: 12 },
  { name: 'Manufacturing engineer', code: 12 },
  { name: 'Manufacturing machine operator', code: 12 },
  { name: 'Manufacturing toolmaker', code: 12 },
  { name: 'Marine scientist', code: 12 },
  { name: 'Market research analyst', code: 12 },
  { name: 'Market research executive', code: 12 },
  { name: 'Marketing account manager', code: 12 },
  { name: 'Marketing assistant', code: 12 },
  { name: 'Marketing executive', code: 12 },
  { name: 'Marketing manager (social media)', code: 12 },
  { name: 'Materials engineer', code: 12 },
  { name: 'Materials specialist', code: 12 },
  { name: 'Mechanical engineer', code: 12 },
  { name: 'Media analyst', code: 12 },
  { name: 'Media buyer', code: 12 },
  { name: 'Media planner', code: 12 },
  { name: 'Medical physicist', code: 12 },
  { name: 'Medical representative', code: 12 },
  { name: 'Mental health nurse', code: 12 },
  { name: 'Metallurgist', code: 12 },
  { name: 'Meteorologist', code: 12 },
  { name: 'Microbiologist', code: 12 },
  { name: 'Midwife', code: 12 },
  { name: 'Mining engineer', code: 12 },
  { name: 'Mobile developer', code: 12 },
  { name: 'Multimedia programmer', code: 12 },
  { name: 'Multimedia specialists', code: 12 },
  { name: 'Museum education officer', code: 12 },
  { name: 'Museum/gallery exhibition officer', code: 12 },
  { name: 'Music therapist', code: 12 },
  { name: 'Nanoscientist', code: 12 },
  { name: 'Nature conservation officer', code: 12 },
  { name: 'Naval architect', code: 12 },
  { name: 'Network administrator', code: 12 },
  { name: 'Nurse', code: 12 },
  { name: 'Nutritional therapist', code: 12 },
  { name: 'Nutritionist', code: 12 },
  { name: 'Occupational therapist', code: 12 },
  { name: 'Oceanographer', code: 12 },
  { name: 'Office manager', code: 12 },
  { name: 'Operational researcher', code: 12 },
  { name: 'Orthoptist', code: 12 },
  { name: 'Outdoor pursuits manager', code: 12 },
  { name: 'Packaging technologist', code: 12 },
  { name: 'Paediatric nurse', code: 12 },
  { name: 'Paramedic', code: 12 },
  { name: 'Patent attorney', code: 12 },
  { name: 'Patent examiner', code: 12 },
  { name: 'Pension scheme manager', code: 12 },
  { name: 'Personal assistant', code: 12 },
  { name: 'Petroleum engineer', code: 12 },
  { name: 'Pharmacist', code: 12 },
  { name: 'Pharmacologist', code: 12 },
  { name: 'Pharmacovigilance officer', code: 12 },
  { name: 'Photographer', code: 12 },
  { name: 'Physiotherapist', code: 12 },
  { name: 'Picture researcher', code: 12 },
  { name: 'Planning and development surveyor', code: 12 },
  { name: 'Planning technician', code: 12 },
  { name: 'Plant breeder', code: 12 },
  { name: 'Police officer', code: 12 },
  { name: 'Political party agent', code: 12 },
  { name: 'Political party research officer', code: 12 },
  { name: 'Practice nurse', code: 12 },
  { name: 'Press photographer', code: 12 },
  { name: 'Press sub-editor', code: 12 },
  { name: 'Prison officer', code: 12 },
  { name: 'Private music teacher', code: 12 },
  { name: 'Probation officer', code: 12 },
  { name: 'Product development scientist', code: 12 },
  { name: 'Production manager', code: 12 },
  { name: 'Programme researcher', code: 12 },
  { name: 'Project manager', code: 12 },
  { name: 'Psychologist (clinical)', code: 12 },
  { name: 'Psychologist (educational)', code: 12 },
  { name: 'Psychotherapist', code: 12 },
  { name: 'Public affairs consultant (lobbyist)', code: 12 },
  { name: 'Public affairs consultant (research)', code: 12 },
  { name: 'Public house manager', code: 12 },
  { name: 'Public librarian', code: 12 },
  { name: 'Public relations (PR) officer', code: 12 },
  { name: 'QA analyst', code: 12 },
  { name: 'Quality assurance manager', code: 12 },
  { name: 'Quantity surveyor', code: 12 },
  { name: 'Records manager', code: 12 },
  { name: 'Recruitment consultant', code: 12 },
  { name: 'Recycling officer', code: 12 },
  { name: 'Regulatory affairs officer', code: 12 },
  { name: 'Research chemist', code: 12 },
  { name: 'Research scientist', code: 12 },
  { name: 'Restaurant manager', code: 12 },
  { name: 'Retail banker', code: 12 },
  { name: 'Retail buyer', code: 12 },
  { name: 'Retail manager', code: 12 },
  { name: 'Retail merchandiser', code: 12 },
  { name: 'Retail pharmacist', code: 12 },
  { name: 'Sales executive', code: 12 },
  { name: 'Sales manager', code: 12 },
  { name: 'Scene of crime officer', code: 12 },
  { name: 'Secretary', code: 12 },
  { name: 'Seismic interpreter', code: 12 },
  { name: 'Site engineer', code: 12 },
  { name: 'Site manager', code: 12 },
  { name: 'Social researcher', code: 12 },
  { name: 'Social worker', code: 12 },
  { name: 'Software developer', code: 12 },
  { name: 'Soil scientist', code: 12 },
  { name: 'Solicitor', code: 12 },
  { name: 'Speech and language therapist', code: 12 },
  { name: 'Sports coach', code: 12 },
  { name: 'Sports development officer', code: 12 },
  { name: 'Sports therapist', code: 12 },
  { name: 'Statistician', code: 12 },
  { name: 'Stockbroker', code: 12 },
  { name: 'Structural engineer', code: 12 },
  { name: 'Systems analyst', code: 12 },
  { name: 'Systems developer', code: 12 },
  { name: 'Tax inspector', code: 12 },
  { name: 'Teacher (nursery/early years)', code: 12 },
  { name: 'Teacher (primary)', code: 12 },
  { name: 'Teacher (secondary)', code: 12 },
  { name: 'Teacher (special educational needs)', code: 12 },
  { name: 'Teaching/classroom assistant', code: 12 },
  { name: 'Technical author', code: 12 },
  { name: 'Technical sales engineer', code: 12 },
  { name: 'TEFL/TESL teacher', code: 12 },
  { name: 'Television production assistant', code: 12 },
  { name: 'Test automation developer', code: 12 },
  { name: 'Tour operator', code: 12 },
  { name: 'Tourism officer', code: 12 },
  { name: 'Tourist information manager', code: 12 },
  { name: 'Town and country planner', code: 12 },
  { name: 'Toxicologist', code: 12 },
  { name: 'Trade union research officer', code: 12 },
  { name: 'Trader', code: 12 },
  { name: 'Trading standards officer', code: 12 },
  { name: 'Training and development officer', code: 12 },
  { name: 'Translator', code: 12 },
  { name: 'Transportation planner', code: 12 },
  { name: 'Travel agent', code: 12 },
  { name: 'TV/film/theatre set designer', code: 12 },
  { name: 'UX designer', code: 12 },
  { name: 'Validation engineer', code: 12 },
  { name: 'Veterinary nurse', code: 12 },
  { name: 'Veterinary surgeon', code: 12 },
  { name: 'Video game designer', code: 12 },
  { name: 'Video game developer', code: 12 },
  { name: 'Volunteer work organiser', code: 12 },
  { name: 'Warehouse manager', code: 12 },
  { name: 'Waste disposal officer', code: 12 },
  { name: 'Water conservation officer', code: 12 },
  { name: 'Water engineer', code: 12 },
  { name: 'Web designer', code: 12 },
  { name: 'Web developer', code: 12 },
  { name: 'Welfare rights adviser', code: 12 },
  { name: 'Writer', code: 12 },
  { name: 'Youth worker', code: 12 },
];
